services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
      - loki-wal:/wal
    command: -config.file=/etc/loki/loki-config.yml
    restart: always

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
    volumes:
      - ./observability/tempo-config.yml:/etc/tempo.yaml
    command: ["--config.file=/etc/tempo.yaml"]

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./observability/otel-collector-config.yml:/etc/otel-collector-config.yml
    command:
      - --config=/etc/otel-collector-config.yml

volumes:
  grafana-storage:
  loki-data:
  loki-wal:
